/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.DefaultPermissionsVM
import cloud.fastreport.model.SubscriptionFolder
import cloud.fastreport.model.SubscriptionPeriodVM
import cloud.fastreport.model.SubscriptionVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param id 
 * @param name 
 * @param locale 
 * @param current 
 * @param old 
 * @param templatesFolder 
 * @param reportsFolder 
 * @param exportsFolder 
 */


interface AdminSubscriptionVM : SubscriptionVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "defaultPermissions")
    val defaultPermissions: DefaultPermissionsVM?
    @Json(name = "ownerId")
    val ownerId: kotlin.String?
}

