/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.FolderCreateVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param name 
 * @param tags 
 * @param icon 
 */


interface AdminFolderCreateVM : FolderCreateVM {

    @Json(name = "parentId")
    val parentId: kotlin.String
    @Json(name = "ownerId")
    val ownerId: kotlin.String
    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "force")
    val force: kotlin.Boolean?
}

