/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.AdminAdministrate
import cloud.fastreport.model.AdminCreate
import cloud.fastreport.model.AdminDelete
import cloud.fastreport.model.AdminExecute
import cloud.fastreport.model.AdminGet
import cloud.fastreport.model.AdminUpdate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param create 
 * @param delete 
 * @param execute 
 * @param get 
 * @param update 
 * @param administrate 
 */


data class AdminPermission (

    @Json(name = "create")
    val create: AdminCreate? = null,

    @Json(name = "delete")
    val delete: AdminDelete? = null,

    @Json(name = "execute")
    val execute: AdminExecute? = null,

    @Json(name = "get")
    val get: AdminGet? = null,

    @Json(name = "update")
    val update: AdminUpdate? = null,

    @Json(name = "administrate")
    val administrate: AdminAdministrate? = null

)

