/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.ProblemLevel
import cloud.fastreport.model.ProblemType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface AnalysisResultVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "level")
    val level: ProblemLevel?
    @Json(name = "detail")
    val detail: kotlin.String?
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String?
    @Json(name = "fileId")
    val fileId: kotlin.String?
    @Json(name = "collectionName")
    val collectionName: kotlin.String?
    @Json(name = "type")
    val type: ProblemType?
    @Json(name = "signature")
    val signature: kotlin.String?
    @Json(name = "newSize")
    val newSize: kotlin.Long?
}

