/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.AuditActionVM
import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface AuditActionsVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "items")
    val items: kotlin.collections.List<AuditActionVM>?
    @Json(name = "hasMore")
    val hasMore: kotlin.Boolean?
    @Json(name = "skip")
    val skip: kotlin.Int?
    @Json(name = "take")
    val take: kotlin.Int?
}

