/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.AuditType
import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface AuditActionVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "userId")
    val userId: kotlin.String?
    @Json(name = "entityId")
    val entityId: kotlin.String?
    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String?
    @Json(name = "type")
    val type: AuditType?
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime?
    @Json(name = "creatorUserId")
    val creatorUserId: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "adminAction")
    val adminAction: kotlin.Boolean?
}

