/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param name 
 * @param email 
 * @param groups 
 * @param subscriptionId 
 * @param createdTime 
 * @param creatorUserId 
 * @param editedTime 
 * @param editorUserId 
 */


data class ContactVM (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "groups")
    val groups: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String? = null,

    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime? = null,

    @Json(name = "creatorUserId")
    val creatorUserId: kotlin.String? = null,

    @Json(name = "editedTime")
    val editedTime: java.time.OffsetDateTime? = null,

    @Json(name = "editorUserId")
    val editorUserId: kotlin.String? = null

)

