/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.ContactGroupVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param groups 
 * @param skip 
 * @param take 
 * @param count 
 */


data class ContactGroupsVM (

    @Json(name = "groups")
    val groups: kotlin.collections.List<ContactGroupVM>? = null,

    @Json(name = "skip")
    val skip: kotlin.Int? = null,

    @Json(name = "take")
    val take: kotlin.Int? = null,

    @Json(name = "count")
    val count: kotlin.Long? = null

)

