/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CreateTaskBaseVM
import cloud.fastreport.model.CreateTransportTaskBaseVM
import cloud.fastreport.model.InputFileVM
import cloud.fastreport.model.OutputFileVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param cronExpression 
 * @param delayedRunTime 
 * @param name 
 * @param subscriptionId 
 */


interface CreateTransformTaskBaseVM : CreateTaskBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "inputFile")
    val inputFile: InputFileVM?
    @Json(name = "locale")
    val locale: kotlin.String?
    @Json(name = "outputFile")
    val outputFile: OutputFileVM?
    @Json(name = "transports")
    val transports: kotlin.collections.List<CreateTransportTaskBaseVM>?
}

