/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface CreateIfNotExistInternalVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "isAdmin")
    val isAdmin: kotlin.Boolean?
    @Json(name = "provider")
    val provider: kotlin.String?
    @Json(name = "refereshToken")
    val refereshToken: kotlin.String?
    @Json(name = "accessToken")
    val accessToken: kotlin.String?
}

