/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.AuditType
import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface CreateAuditActionVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "userId")
    val userId: kotlin.String?
    @Json(name = "entityId")
    val entityId: kotlin.String?
    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String?
    @Json(name = "type")
    val type: AuditType?
    @Json(name = "messageId")
    val messageId: kotlin.String?
    @Json(name = "fileName")
    val fileName: kotlin.String?
}

