/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface CreateSubscriptionVM : CloudBaseVM {

    @Json(name = "planId")
    val planId: kotlin.String
    @Json(name = "name")
    val name: kotlin.String
    @Json(name = "userId")
    val userId: kotlin.String
    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "start")
    val start: java.time.OffsetDateTime?
    @Json(name = "end")
    val end: java.time.OffsetDateTime?
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>?
}

