/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.DataSourceConnectionType
import cloud.fastreport.model.DataSourceStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface DataSourceVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "connectionType")
    val connectionType: DataSourceConnectionType?
    @Json(name = "connectionString")
    val connectionString: kotlin.String?
    @Json(name = "dataStructure")
    val dataStructure: kotlin.String?
    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String?
    @Json(name = "editedTime")
    val editedTime: java.time.OffsetDateTime?
    @Json(name = "editorUserId")
    val editorUserId: kotlin.String?
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime?
    @Json(name = "creatorUserId")
    val creatorUserId: kotlin.String?
    @Json(name = "status")
    val status: DataSourceStatus?
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String?
}

