/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface DataSourceSelectCommandParameterVM : CloudBaseVM {

    @Json(name = "name")
    val name: kotlin.String
    @Json(name = "dataType")
    val dataType: kotlin.String
    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "defaultValue")
    val defaultValue: kotlin.String?
    @Json(name = "size")
    val propertySize: kotlin.Int?
}

