/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.DataSourceSelectCommandParameterVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface DataSourceSelectCommandVM : CloudBaseVM {

    @Json(name = "name")
    val name: kotlin.String
    @Json(name = "command")
    val command: kotlin.String
    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "parameters")
    val parameters: kotlin.collections.List<DataSourceSelectCommandParameterVM>?
}

