/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.ExportFormat

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface ExportTemplateVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "fileName")
    val fileName: kotlin.String?
    @Json(name = "folderId")
    val folderId: kotlin.String?
    @Json(name = "locale")
    val locale: kotlin.String?
    @Json(name = "pagesCount")
    val pagesCount: kotlin.Int?
    @Json(name = "format")
    val format: ExportFormat?
    @Json(name = "exportParameters")
    val exportParameters: kotlin.collections.Map<kotlin.String, kotlin.String>?
    @Json(name = "reportParameters")
    val reportParameters: kotlin.collections.Map<kotlin.String, kotlin.String>?
}

