/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.ExportFormat
import cloud.fastreport.model.InputFileVM
import cloud.fastreport.model.OutputFileVM
import cloud.fastreport.model.TaskEnd
import cloud.fastreport.model.TransformTaskBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param inputFile 
 * @param locale 
 * @param outputFile 
 * @param transportIds 
 * @param cronExpression 
 * @param startsOn 
 * @param ends 
 * @param id 
 * @param name 
 * @param recurrentRunTime 
 * @param recurrentWasRunTime 
 * @param subscriptionId 
 */


interface ExportReportTaskVM : TransformTaskBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "exportParameters")
    val exportParameters: kotlin.collections.Map<kotlin.String, kotlin.String>?
    @Json(name = "format")
    val format: ExportFormat?
    @Json(name = "pagesCount")
    val pagesCount: kotlin.Int?
}

