/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.FileVM
import cloud.fastreport.model.FilesVMBase

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param files 
 * @param count 
 * @param skip 
 * @param take 
 */


interface FilesVM : FilesVMBase {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
}

