/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.FilePermissionCRUDVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface FilePermissionsCRUDVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "ownerId")
    val ownerId: kotlin.String?
    @Json(name = "owner")
    val owner: FilePermissionCRUDVM?
    @Json(name = "groups")
    val groups: kotlin.collections.Map<kotlin.String, FilePermissionCRUDVM>?
    @Json(name = "other")
    val other: FilePermissionCRUDVM?
    @Json(name = "anon")
    val anon: FilePermissionCRUDVM?
}

