/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.FileStatus
import cloud.fastreport.model.FileStatusReason

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface FileStatusUpdateInternalVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "status")
    val status: FileStatus?
    @Json(name = "reason")
    val reason: FileStatusReason?
    @Json(name = "editorId")
    val editorId: kotlin.String?
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String?
}

