/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.FileStatus
import cloud.fastreport.model.FileStatusReason
import cloud.fastreport.model.FileType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface FileVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "createdTime")
    val createdTime: java.time.OffsetDateTime?
    @Json(name = "creatorUserId")
    val creatorUserId: kotlin.String?
    @Json(name = "editedTime")
    val editedTime: java.time.OffsetDateTime?
    @Json(name = "editorUserId")
    val editorUserId: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "parentId")
    val parentId: kotlin.String?
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>?
    @Json(name = "icon")
    val icon: kotlin.ByteArray?
    @Json(name = "type")
    val type: FileType?
    @Json(name = "size")
    val propertySize: kotlin.Long?
    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String?
    @Json(name = "status")
    val status: FileStatus?
    @Json(name = "statusReason")
    val statusReason: FileStatusReason?
    @Json(name = "errorMessage")
    val errorMessage: kotlin.String?
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean?
}

