/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.FileAdministrate
import cloud.fastreport.model.FileCreate
import cloud.fastreport.model.FileDelete
import cloud.fastreport.model.FileExecute
import cloud.fastreport.model.FileGet
import cloud.fastreport.model.FileUpdate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface FilePermissionCRUDVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "create")
    val create: FileCreate?
    @Json(name = "delete")
    val delete: FileDelete?
    @Json(name = "execute")
    val execute: FileExecute?
    @Json(name = "get")
    val get: FileGet?
    @Json(name = "update")
    val update: FileUpdate?
    @Json(name = "administrate")
    val administrate: FileAdministrate?
}

