/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.GroupAdministrate
import cloud.fastreport.model.GroupCreate
import cloud.fastreport.model.GroupDelete
import cloud.fastreport.model.GroupExecute
import cloud.fastreport.model.GroupGet
import cloud.fastreport.model.GroupUpdate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface GroupPermissionCRUDVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "create")
    val create: GroupCreate?
    @Json(name = "delete")
    val delete: GroupDelete?
    @Json(name = "execute")
    val execute: GroupExecute?
    @Json(name = "get")
    val get: GroupGet?
    @Json(name = "update")
    val update: GroupUpdate?
    @Json(name = "administrate")
    val administrate: GroupAdministrate?
}

