/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.DataSourcePermissionCRUDVM
import cloud.fastreport.model.FilePermissionCRUDVM
import cloud.fastreport.model.GroupPermissionCRUDVM
import cloud.fastreport.model.SubscriptionPermissionCRUDVM
import cloud.fastreport.model.TaskPermissionCRUDVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface MyPermissionsVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "subscription")
    val subscription: SubscriptionPermissionCRUDVM?
    @Json(name = "files")
    val files: FilePermissionCRUDVM?
    @Json(name = "datasources")
    val datasources: DataSourcePermissionCRUDVM?
    @Json(name = "groups")
    val groups: GroupPermissionCRUDVM?
    @Json(name = "tasks")
    val tasks: TaskPermissionCRUDVM?
}

