/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: anonPermissions,unrelatedFiles,otherWithoutGet,deadSubInUser,emptySub,lostFileChunks,wrongSubscripitonSizes,filesWithoutChunks
 */

@JsonClass(generateAdapter = false)
enum class ProblemType(val value: kotlin.String) {

    @Json(name = "AnonPermissions")
    anonPermissions("AnonPermissions"),

    @Json(name = "UnrelatedFiles")
    unrelatedFiles("UnrelatedFiles"),

    @Json(name = "OtherWithoutGet")
    otherWithoutGet("OtherWithoutGet"),

    @Json(name = "DeadSubInUser")
    deadSubInUser("DeadSubInUser"),

    @Json(name = "EmptySub")
    emptySub("EmptySub"),

    @Json(name = "LostFileChunks")
    lostFileChunks("LostFileChunks"),

    @Json(name = "WrongSubscripitonSizes")
    wrongSubscripitonSizes("WrongSubscripitonSizes"),

    @Json(name = "FilesWithoutChunks")
    filesWithoutChunks("FilesWithoutChunks");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ProblemType) "$data" else null

        /**
         * Returns a valid [ProblemType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ProblemType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

