/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.SaveMode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param author 
 * @param created 
 * @param creatorVersion 
 * @param description 
 * @param modified 
 * @param name 
 * @param picture 
 * @param previewPictureRatio 
 * @param saveMode 
 * @param savePreviewPicture 
 * @param tag 
 * @param version 
 */


data class ReportInfo (

    @Json(name = "author")
    val author: kotlin.String? = null,

    @Json(name = "created")
    val created: java.time.OffsetDateTime? = null,

    @Json(name = "creatorVersion")
    val creatorVersion: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "modified")
    val modified: java.time.OffsetDateTime? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "picture")
    val picture: kotlin.ByteArray? = null,

    @Json(name = "previewPictureRatio")
    val previewPictureRatio: kotlin.Float? = null,

    @Json(name = "saveMode")
    val saveMode: SaveMode? = null,

    @Json(name = "savePreviewPicture")
    val savePreviewPicture: kotlin.Boolean? = null,

    @Json(name = "tag")
    val tag: kotlin.String? = null,

    @Json(name = "version")
    val version: kotlin.String? = null

)

