/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.OutputFileVM
import cloud.fastreport.model.RunExportReportTaskVM
import cloud.fastreport.model.RunInputFileVM
import cloud.fastreport.model.RunTransformTaskBaseVM
import cloud.fastreport.model.RunTransportTaskBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param inputFile 
 * @param locale 
 * @param outputFile 
 * @param transports 
 * @param subscriptionId 
 */


interface RunPrepareTemplateTaskVM : RunTransformTaskBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "exports")
    val exports: kotlin.collections.List<RunExportReportTaskVM>?
    @Json(name = "pagesCount")
    val pagesCount: kotlin.Int?
    @Json(name = "reportParameters")
    val reportParameters: kotlin.collections.Map<kotlin.String, kotlin.String>?
}

