/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.OutputFileVM
import cloud.fastreport.model.RunInputFileVM
import cloud.fastreport.model.RunTaskBaseVM
import cloud.fastreport.model.RunTransportTaskBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param subscriptionId 
 */


interface RunTransformTaskBaseVM : RunTaskBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "inputFile")
    val inputFile: RunInputFileVM?
    @Json(name = "locale")
    val locale: kotlin.String?
    @Json(name = "outputFile")
    val outputFile: OutputFileVM?
    @Json(name = "transports")
    val transports: kotlin.collections.List<RunTransportTaskBaseVM>?
}

