/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: all,original,user,role,security,deny,custom
 */

@JsonClass(generateAdapter = false)
enum class SaveMode(val value: kotlin.String) {

    @Json(name = "All")
    all("All"),

    @Json(name = "Original")
    original("Original"),

    @Json(name = "User")
    user("User"),

    @Json(name = "Role")
    role("Role"),

    @Json(name = "Security")
    security("Security"),

    @Json(name = "Deny")
    deny("Deny"),

    @Json(name = "Custom")
    custom("Custom");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SaveMode) "$data" else null

        /**
         * Returns a valid [SaveMode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SaveMode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

