/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param folderId 
 * @param bytesUsed 
 */


data class SubscriptionFolder (

    @Json(name = "folderId")
    val folderId: kotlin.String? = null,

    @Json(name = "bytesUsed")
    val bytesUsed: kotlin.Long? = null

)

