/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.InvitedUser

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface SubscriptionInviteVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "usages")
    val usages: kotlin.Long?
    @Json(name = "durable")
    val durable: kotlin.Boolean?
    @Json(name = "accessToken")
    val accessToken: kotlin.String?
    @Json(name = "expiredDate")
    val expiredDate: java.time.OffsetDateTime?
    @Json(name = "addedUsers")
    val addedUsers: kotlin.collections.List<InvitedUser>?
    @Json(name = "creatorUserId")
    val creatorUserId: kotlin.String?
}

