/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.SubscriptionAdministrate
import cloud.fastreport.model.SubscriptionCreate
import cloud.fastreport.model.SubscriptionDelete
import cloud.fastreport.model.SubscriptionExecute
import cloud.fastreport.model.SubscriptionGet
import cloud.fastreport.model.SubscriptionUpdate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface SubscriptionPermissionCRUDVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "create")
    val create: SubscriptionCreate?
    @Json(name = "delete")
    val delete: SubscriptionDelete?
    @Json(name = "execute")
    val execute: SubscriptionExecute?
    @Json(name = "get")
    val get: SubscriptionGet?
    @Json(name = "update")
    val update: SubscriptionUpdate?
    @Json(name = "administrate")
    val administrate: SubscriptionAdministrate?
}

