/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.SubscriptionFolder
import cloud.fastreport.model.SubscriptionPeriodVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface SubscriptionVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "locale")
    val locale: kotlin.String?
    @Json(name = "current")
    val current: SubscriptionPeriodVM?
    @Json(name = "old")
    val old: kotlin.collections.List<SubscriptionPeriodVM>?
    @Json(name = "templatesFolder")
    val templatesFolder: SubscriptionFolder?
    @Json(name = "reportsFolder")
    val reportsFolder: SubscriptionFolder?
    @Json(name = "exportsFolder")
    val exportsFolder: SubscriptionFolder?
}

