/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.TaskEnd

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface TaskBaseVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "cronExpression")
    val cronExpression: kotlin.String?
    @Json(name = "startsOn")
    val startsOn: java.time.OffsetDateTime?
    @Json(name = "ends")
    val ends: TaskEnd?
    @Json(name = "id")
    val id: kotlin.String?
    @Json(name = "name")
    val name: kotlin.String?
    @Json(name = "recurrentRunTime")
    val recurrentRunTime: java.time.OffsetDateTime?
    @Json(name = "recurrentWasRunTime")
    val recurrentWasRunTime: java.time.OffsetDateTime?
    @Json(name = "subscriptionId")
    val subscriptionId: kotlin.String?
}

