/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface TaskSettingsVM : CloudBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "prepare")
    val prepare: kotlin.Boolean?
    @Json(name = "exportTemplate")
    val exportTemplate: kotlin.Boolean?
    @Json(name = "exportReport")
    val exportReport: kotlin.Boolean?
    @Json(name = "sendViaEmail")
    val sendViaEmail: kotlin.Boolean?
    @Json(name = "uploadToFTP")
    val uploadToFTP: kotlin.Boolean?
    @Json(name = "sendViaWebhook")
    val sendViaWebhook: kotlin.Boolean?
    @Json(name = "fetchData")
    val fetchData: kotlin.Boolean?
    @Json(name = "thumbnailReport")
    val thumbnailReport: kotlin.Boolean?
    @Json(name = "thumbnailTemplate")
    val thumbnailTemplate: kotlin.Boolean?
}

