/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.TaskBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param cronExpression 
 * @param delayedRunTime 
 * @param delayedWasRunTime 
 * @param id 
 * @param name 
 * @param recurrentRunTime 
 * @param recurrentWasRunTime 
 * @param subscriptionId 
 */


interface ThumbnailReportTaskVM : TaskBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "reportId")
    val reportId: kotlin.String?
}

