/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: second,minute,hour,day,week,month,year
 */

@JsonClass(generateAdapter = false)
enum class TimePeriodType(val value: kotlin.String) {

    @Json(name = "Second")
    second("Second"),

    @Json(name = "Minute")
    minute("Minute"),

    @Json(name = "Hour")
    hour("Hour"),

    @Json(name = "Day")
    day("Day"),

    @Json(name = "Week")
    week("Week"),

    @Json(name = "Month")
    month("Month"),

    @Json(name = "Year")
    year("Year");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TimePeriodType) "$data" else null

        /**
         * Returns a valid [TimePeriodType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TimePeriodType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

