/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CreateTaskEndVM
import cloud.fastreport.model.ExportFormat
import cloud.fastreport.model.InputFileVM
import cloud.fastreport.model.OutputFileVM
import cloud.fastreport.model.UpdateExportReportTaskVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param exportParameters 
 * @param format 
 * @param pagesCount 
 * @param inputFile 
 * @param locale 
 * @param outputFile 
 * @param transportIds 
 * @param cronExpression 
 * @param startsOn 
 * @param ends 
 * @param name 
 */


interface UpdateExportTemplateTaskVM : UpdateExportReportTaskVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "reportParameters")
    val reportParameters: kotlin.collections.Map<kotlin.String, kotlin.String>?
}

