/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.CloudBaseVM
import cloud.fastreport.model.UpdateDataSourcePermissionsVM
import cloud.fastreport.model.UpdateFilePermissionsVM
import cloud.fastreport.model.UpdateGroupPermissionsVM
import cloud.fastreport.model.UpdateTaskPermissionsVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 */


interface UpdateDefaultPermissionsVM : CloudBaseVM {

    @Json(name = "\$t")
    val dollarT: kotlin.String
    @Json(name = "filePermissions")
    val filePermissions: UpdateFilePermissionsVM?
    @Json(name = "groupPermissions")
    val groupPermissions: UpdateGroupPermissionsVM?
    @Json(name = "dataSourcePermissions")
    val dataSourcePermissions: UpdateDataSourcePermissionsVM?
    @Json(name = "taskPermissions")
    val taskPermissions: UpdateTaskPermissionsVM?
}

