/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package cloud.fastreport.model

import cloud.fastreport.model.InputFileVM
import cloud.fastreport.model.OutputFileVM
import cloud.fastreport.model.UpdateTaskBaseVM

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param dollarT 
 * @param cronExpression 
 * @param delayedRunTime 
 * @param name 
 */


interface UpdateTransformTaskBaseVM : UpdateTaskBaseVM {

    @Json(name = "\$t")
    override val dollarT: kotlin.String
    @Json(name = "inputFile")
    val inputFile: InputFileVM?
    @Json(name = "locale")
    val locale: kotlin.String?
    @Json(name = "outputFile")
    val outputFile: OutputFileVM?
    @Json(name = "transportIds")
    val transportIds: kotlin.collections.List<kotlin.String>?
}

